author: M. Grady Saunders
source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
includes_dir: ./_includes
encoding: "utf-8"
markdown: kramdown
markdown_ext: "markdown,md"
liquid:
    error_mode: strict

